### ISSUE TITLE
Tile menu missing

### ISSUE THREAD

**Issue by michass** [EdddieN/machinon-domoticz_theme#183] opened 2018-11-23 06:51 UTC
Hi, where can I found Tile menu, stats and etc?
In new updates of each branch are missed:
![image](https://user-images.githubusercontent.com/43785139/48931051-a1df5880-eef4-11e8-994a-756aca38eee4.png)

**Comment by EdddieN** [comment] 2018-11-23 17:14
Is this beta or master?

Also, make sure you clear you cache and reset settings

**Comment by EdddieN** [comment] 2018-11-23 17:15
Also are you running behind proxy? or remote access?

Just tried master copy and after a refresh the menu is there

**Comment by michass** [comment] 2018-11-25 21:36
Remote and local. From internet Explorer to opera. Mobile and desktop. Refresh don't work.
Master and beta.

**Comment by EdddieN** [comment] 2018-11-26 12:46
I cannot reproduce it, I think it is best to put it on the forum post and see if more people have the same issue?

Only few users report here

**Comment by michass** [comment] 2018-11-28 18:13
anybody else?

**Comment by landaisbenj** [comment] 2018-11-28 18:30
I have it one time couple monce ago. But it disappear after master update.

**Comment by michass** [comment] 2018-11-28 19:13
I have master, beta, removed, and clone again. still the same

**Comment by landaisbenj** [comment] 2018-11-28 19:34
It's your lan network ?

**Comment by michass** [comment] 2018-11-28 19:42
yes, mine

**Comment by landaisbenj** [comment] 2018-11-28 20:14
Do you know js or jquery ?

**Comment by landaisbenj** [comment] 2018-11-28 20:16
What is your screen resolution ?

**Comment by michass** [comment] 2018-11-29 16:40
I don't know js and jquery.
I have this issue on each device, 1920x1080
1280x720 and 2160x1440 or somthing. It's not device, network issue, but domoticz/theme.

**Comment by landaisbenj** [comment] 2018-11-30 17:09
Ok maybe it's this :https://github.com/EdddieN/machinon-domoticz_theme/blob/5c84ef1f96dbe4533fca93256ef57cb9e4e23592/custom.css#L437 
can you confirm the line 437 on your custom.css ?

**Comment by michass** [comment] 2018-12-03 07:05
confirmed!
`  display: none;`

**Comment by michass** [comment] 2018-12-21 10:12
anybody?
When i want to go to logs, or edit something i need to switch to other theme.

**Comment by EdddieN** [comment] 2018-12-21 11:44
I don't get it... have  you tried master, beta and even Xmas branch?

**Comment by EdddieN** [comment] 2019-01-02 18:15
Probably has to do with this: https://github.com/EdddieN/machinon-domoticz_theme/issues/184

**Comment by DewGew** [comment] 2019-01-31 09:47
This is fixed here https://github.com/EdddieN/machinon-domoticz_theme/issues/184#issuecomment-459272314 . A fix is commited to beta.
closing this issue 👍

**Closed by DewGew** 2019-01-31 09:47 UTC
